version: "3.1"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./evieData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= Evie
    ports:
      - 27017:27017